name: 张家治的个人博客
author: 张家治

highlighter: rouge

gems: [jekyll-paginate]

paginate: 5
paginate_path: "/blog/page:num"

excerpt_separator: "<!-- more -->"

github_page: https://github.com/cosmozhang1995

url: https://www.cosmozhang.com

timezone: Asia/Shanghai
