name: 张家治的个人博客
author: 张家治

highlighter: pygments

gems: [jekyll-paginate]

paginate: 5
paginate_path: "/blog/page:num"

github_page: https://github.com/cosmozhang1995
codingnet_page: https://coding.net/u/cosmozhang1995